Map<String, String> languageTrainedDataMap = {
  'Afrikaans': 'afr.traineddata',
  'Amharic': 'amh.traineddata',
  'Arabic': 'ara.traineddata',
  'Assamese': 'asm.traineddata',
  'Azerbaijani': 'aze.traineddata',
  'Azerbaijani (Cyrillic)': 'aze_cyrl.traineddata',
  'Belarusian': 'bel.traineddata',
  'Bengali': 'ben.traineddata',
  'Tibetan': 'bod.traineddata',
  'Bosnian': 'bos.traineddata',
  'Breton': 'bre.traineddata',
  'Bulgarian': 'bul.traineddata',
  'Catalan': 'cat.traineddata',
  'Cebuano': 'ceb.traineddata',
  'Czech': 'ces.traineddata',
  'Simplified Chinese': 'chi_sim.traineddata',
  'Simplified Chinese (vertical)': 'chi_sim_vert.traineddata',
  'Traditional Chinese': 'chi_tra.traineddata',
  'Traditional Chinese (vertical)': 'chi_tra_vert.traineddata',
  'Cherokee': 'chr.traineddata',
  'Corsican': 'cos.traineddata',
  'Welsh': 'cym.traineddata',
  'Danish': 'dan.traineddata',
  'Danish (Fraktur)': 'dan_frak.traineddata',
  'German': 'deu.traineddata',
  'German (Fraktur)': 'deu_frak.traineddata',
  'Divehi': 'div.traineddata',
  'Dzongkha': 'dzo.traineddata',
  'Greek': 'ell.traineddata',
  'English': 'eng.traineddata',
  'Middle English': 'enm.traineddata',
  'Esperanto': 'epo.traineddata',
  'Mathematical Equations': 'equ.traineddata',
  'Estonian': 'est.traineddata',
  'Basque': 'eus.traineddata',
  'Faroese': 'fao.traineddata',
  'Persian': 'fas.traineddata',
  'Filipino': 'fil.traineddata',
  'Finnish': 'fin.traineddata',
  'French': 'fra.traineddata',
  'Frankish': 'frk.traineddata',
  'Middle French': 'frm.traineddata',
  'Frisian': 'fry.traineddata',
  'Scottish Gaelic': 'gla.traineddata',
  'Irish': 'gle.traineddata',
  'Galician': 'glg.traineddata',
  'Ancient Greek': 'grc.traineddata',
  'Gujarati': 'guj.traineddata',
  'Haitian Creole': 'hat.traineddata',
  'Hebrew': 'heb.traineddata',
  'Hindi': 'hin.traineddata',
  'Croatian': 'hrv.traineddata',
  'Hungarian': 'hun.traineddata',
  'Armenian': 'hye.traineddata',
  'Inuktitut': 'iku.traineddata',
  'Indonesian': 'ind.traineddata',
  'Icelandic': 'isl.traineddata',
  'Italian': 'ita.traineddata',
  'Old Italian': 'ita_old.traineddata',
  'Javanese': 'jav.traineddata',
  'Japanese': 'jpn.traineddata',
  'Japanese (vertical)': 'jpn_vert.traineddata',
  'Kannada': 'kan.traineddata',
  'Georgian': 'kat.traineddata',
  'Old Georgian': 'kat_old.traineddata',
  'Kazakh': 'kaz.traineddata',
  'Khmer': 'khm.traineddata',
  'Kirghiz': 'kir.traineddata',
  'Kurdish': 'kmr.traineddata',
  'Korean': 'kor.traineddata',
  'Korean (vertical)': 'kor_vert.traineddata',
  'Lao': 'lao.traineddata',
  'Latin': 'lat.traineddata',
  'Latvian': 'lav.traineddata',
  'Lithuanian': 'lit.traineddata',
  'Luxembourgish': 'ltz.traineddata',
  'Malayalam': 'mal.traineddata',
  'Marathi': 'mar.traineddata',
  'Macedonian': 'mkd.traineddata',
  'Maltese': 'mlt.traineddata',
  'Mongolian': 'mon.traineddata',
  'Maori': 'mri.traineddata',
  'Malay': 'msa.traineddata',
  'Burmese': 'mya.traineddata',
  'Nepali': 'nep.traineddata',
  'Dutch': 'nld.traineddata',
  'Norwegian': 'nor.traineddata',
  'Occitan': 'oci.traineddata',
  'Oriya': 'ori.traineddata',
  'Orientation and Script Detection': 'osd.traineddata',
  'Punjabi': 'pan.traineddata',
  'PDF Font File': 'pdf.ttf',
  'Polish': 'pol.traineddata',
  'Portuguese': 'por.traineddata',
  'Pashto': 'pus.traineddata',
  'Quechua': 'que.traineddata',
  'Romanian': 'ron.traineddata',
  'Russian': 'rus.traineddata',
  'Sanskrit': 'san.traineddata',
  'Sinhala': 'sin.traineddata',
  'Slovak': 'slk.traineddata',
  'Slovak (Fraktur)': 'slk_frak.traineddata',
  'Slovenian': 'slv.traineddata',
  'Sindhi': 'snd.traineddata',
  'Spanish': 'spa.traineddata',
  'Old Spanish': 'spa_old.traineddata',
  'Albanian': 'sqi.traineddata',
  'Serbian': 'srp.traineddata',
  'Serbian (Latin)': 'srp_latn.traineddata',
  'Sundanese': 'sun.traineddata',
  'Swahili': 'swa.traineddata',
  'Swedish': 'swe.traineddata',
  'Syriac': 'syr.traineddata',
  'Tamil': 'tam.traineddata',
  'Tatar': 'tat.traineddata',
  'Telugu': 'tel.traineddata',
  'Tajik': 'tgk.traineddata',
  'Tagalog': 'tgl.traineddata',
  'Thai': 'tha.traineddata',
  'Tigrinya': 'tir.traineddata',
  'Tongan': 'ton.traineddata',
  'Turkish': 'tur.traineddata',
  'Uighur': 'uig.traineddata',
  'Ukrainian': 'ukr.traineddata',
  'Urdu': 'urd.traineddata',
  'Uzbek': 'uzb.traineddata',
  'Uzbek (Cyrillic)': 'uzb_cyrl.traineddata',
  'Vietnamese': 'vie.traineddata',
  'Yiddish': 'yid.traineddata',
  'Yoruba': 'yor.traineddata'
};
