name: dictator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_tesseract_ocr: ^0.4.23
  permission_handler: ^10.4.1
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15
  image_picker: ^1.0.0
  flutter_tts: ^3.7.0
  provider: ^6.0.5
  uuid: ^3.0.7
  hive: ^2.2.3
  intl: ^0.18.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
